//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QIRC.Commands {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QIRC.Commands.Words", typeof(Words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A
        ///A&apos;asia
        ///A&apos;s
        ///AA
        ///AA&apos;s
        ///AAA
        ///AAAA
        ///AAAAAA
        ///AAAL
        ///AAAS
        ///AAE
        ///AAEE
        ///AAF
        ///AAG
        ///AAII
        ///AAM
        ///AAMSI
        ///AAO
        ///AAP
        ///AAPSS
        ///AARC
        ///AARP
        ///AARP&apos;s
        ///AAS
        ///AAS&apos;s
        ///AATech
        ///AATech&apos;s
        ///AAU
        ///AAUP
        ///AAUW
        ///AAVSO
        ///AAX
        ///AAeE
        ///AAeE&apos;s
        ///AAgr
        ///AAgr&apos;s
        ///AAvTech
        ///AAvTech&apos;s
        ///AB
        ///AB&apos;s
        ///ABA
        ///ABATS
        ///ABBR
        ///ABC
        ///ABC&apos;s
        ///ABCs
        ///ABD
        ///ABD&apos;s
        ///ABDs
        ///ABEL
        ///ABEPP
        ///ABEd
        ///ABEd&apos;s
        ///ABFM
        ///ABHC
        ///ABI
        ///ABLS
        ///ABLS&apos;s
        ///ABM
        ///ABM&apos;s
        ///ABMs
        ///ABPC
        ///ABS
        ///ABSBH
        ///ABus
        ///ABus&apos;s
        ///AC
        ///AC&apos;s
        ///ACAA
        ///ACAS
        ///ACAWS
        ///ACB
        ///ACBL
        ///ACC
        ///ACCRA
        ///ACCS
        ///ACCT
        ///ACD
        ///ACDA
        ///ACE
        ///ACF
        ///ACGI
        ///ACH
        ///ACHEFT
        ///ACK
        ///ACL
        ///ACLS
        ///ACLU
        ///ACLU&apos;s
        ///ACM
        ///ACO
        ///ACOF
        ///ACP
        ///ACRNEMA
        ///ACRV
        ///ACS
        ///ACSE
        ///ACSNET
        ///ACSU
        ///ACT
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
